# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170512_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='catagories',
            field=models.ManyToManyField(to='blog.Catagory'),
        ),
        migrations.AddField(
            model_name='question',
            name='catagories',
            field=models.ManyToManyField(to='blog.Catagory'),
        ),
    ]
