# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='catagories',
            field=models.ManyToManyField(to='polls.Catagory'),
        ),
    ]
